refresh_rate: 30 seconds
appenders:
  stdout:
    kind: "console"
  requests:
    kind: file
    path: "log/rproxifier.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: debug
  app::requests:
    level: debug
    appenders:
      - stdout
    additive: true